### PR TITLE
fix(fetch): prevent error when tmp is null

### PR DESCRIPTION
**Pull request by jeremyvergnas**
fix(fetch): prevent error when tmp is null

### CODE REVIEW

**Comment by RWOverdijk** [comment]
This only happens when `this.data;` is empty. I'd prefer a check on that, I can't merge this pr.

**Comment by jeremyvergnas** [comment]
@RWOverdijk It can happen (and it actually happens) even is `this.data` is not empty as the value of  `tmp` is changed here:
https://github.com/SpoonX/homefront/pull/13/files#diff-168726dbe96b3ce427e7fedce31bb0bcR213

**Comment by jeremyvergnas** [comment]
I could also do the check in the for loop to check if the value that will be assigned to `tmp` is not null (`tmp[keys[i]] === null`), something like this:
```
if (typeof tmp[keys[i]] === 'undefined' || tmp[keys[i]] === null) {
  return defaultValue;
}
```

**Comment by jeremyvergnas** [comment]
I changed the check to prevent an error in case of tmp equals `false` or is `null` for instance

**Pull request merged**
